baseURL = "https://venukrish.com/"
locale = "en-us"
title = "Venu Krishnamurthy"
theme = "venu"

[params]
  description = "Pipeline TD at Weta FX. Writing about VFX, code, and everything else."
  author = "Venu Krishnamurthy"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Interests"
    url = "/interests/"
    weight = 2
  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 3
  [[menu.main]]
    name = "Musings"
    url = "/musings/"
    weight = 4

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true